### ISSUE TITLE
Fuzzy matching changing genus 

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/ala-name-matching#24]
Thenus orientalis (Moreton Bay bug?) incorrectly changed to Thunnus orientalis (Northern Bluefin Tuna).

Suggest changing test from `fuzzy genus + fuzzy species` to `exact genus + fuzzy species` then `exact genus` then `fuzzy genus + fuzzy species`.

**Comment by adam-collins** [comment]
Moved from https://github.com/AtlasOfLivingAustralia/biocache-store/issues/17

**Comment by djtfmartin** [comment]
This makes sense to me.

Any thoughts @charvolant  ?

**Comment by charvolant** [comment]
Makes sense to me. I might try it out and see what other oddities get produced.

In the long term, I think the name matching could do with an overhaul where we get a bunch of results which match all possibilities and then winnow them, rather than try one after the other. That way, we can use higher-order hints to steer the fuzzy matching a bit more.
